runtime: python39
instance_class: F1 
automatic_scaling:
  target_cpu_utilization: 0.5  
  min_instances: 2
  max_instances: 3
  min_idle_instances: 2 
  max_idle_instances: 3 
  min_pending_latency: 30ms 
  max_pending_latency: 100ms
  max_concurrent_requests: 10